#!/bin/env python3
import glob
import subprocess
import os
import sys

def mp4_string(title):
    name, name_extention=os.path.splitext(os.path.basename(title).replace("'","\\'",))
    return name

def mkv_string(title):
    name, name_extention=os.path.splitext(os.path.basename(title))
    return name

def exec_mp4(mp4name):
    mp4name_title=mp4_string(mp4name)
    subprocess.run(["kid3-cli", "-c", f"set title '{mp4name_title}'", mp4name])

def mp4(recursive=False):
    if recursive:
        for mp4name in glob.glob('**/*.mp4', recursive=True):
            exec_mp4(mp4name)
            print(f"Title metadata of {mp4name} has been changed")
    else:
        for mp4name in glob.glob("*.mp4"):
            exec_mp4(mp4name)
            print(f"Title metadata of {mp4name} has been changed")

def exec_mkv(mkvname):
    mkvname_title=mkv_string(mkvname)
    subprocess.run(["mkvpropedit", "-e", "info", "-s", f"title={mkvname_title}", mkvname])

def mkv(recursive=False):
    if recursive:
        for mkvname in glob.glob('**/*.mkv', recursive=True):
            exec_mkv(mkvname)
    else:
        for mkvname in glob.glob("*.mkv"):
            exec_mkv(mkvname)

if len(sys.argv) < 2:
    print("Usage: rmeta mkv|mp4|all append -r for recursive operations")
    sys.exit(1)

action_type = sys.argv[1]
recursive = False
if len(sys.argv) > 2 and sys.argv[2] == "-r":
    recursive=True
if action_type == "mkv":
    mkv(recursive)
elif action_type =="mp4":
    mp4(recursive)
elif action_type =="all":
    mkv(recursive)
    mp4(recursive)
else:
    print("Usage: rmeta mkv|mp4|all append -r for recursive operations")
    sys.exit(1)
